[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "nwparray"
dynamic = ["version"]
description = 'Tool for downloading weather forecast datasets '
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = []
authors = [
  { name = "William May", email = "wmay@hey.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "dask",
  "distributed",
  "herbie-data",
  "humanize",
  "numpy",
  "pandas",
  "requests"
]

[project.optional-dependencies]

[project.urls]
Documentation = "https://github.com/ASRCsoft/nwparray#readme"
Issues = "https://github.com/ASRCsoft/nwparray/issues"
Source = "https://github.com/ASRCsoft/nwparray"

[tool.hatch.version]
path = "src/nwparray/__about__.py"

[tool.hatch.envs.default]
dependencies = [
  "bokeh >= 3.1.0",
  "ipython"
]

[tool.hatch.envs.conda]
type = "conda"
python = "3.10"
environment-file = "environment.yml"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/nwparray tests}"

[tool.coverage.run]
source_pkgs = ["nwparray", "tests"]
branch = true
parallel = true
omit = [
  "src/nwparray/__about__.py",
]

[tool.coverage.paths]
nwparray = ["src/nwparray", "*/nwparray/src/nwparray"]
tests = ["tests", "*/nwparray/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[tool.pixi.dependencies]
wgrib2 = "*"
grib2io = "*"

[tool.pixi.pypi-dependencies]
ipython = "*"
nwparray = { path = ".", editable = true }

[tool.pixi.environments]
default = { solve-group = "default" }

[tool.pixi.tasks]
